config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'posts#index'
  resources :posts do
    resources :comments
    resources :likes
  end
  resources :histories
  get 'tags/:tag', to: 'posts#index', as: :tag
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/history.rb
class History < ApplicationRecord
  has_one_attached :image
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, presence: true #проверка на не пустое значение
  belongs_to :user
  has_one_attached :image #ActiveStorage
  has_many :comments
  has_many :likes
  acts_as_taggable
  enum status: [:on_moderetion, :published, :hidden] #enum
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :likes
  enum status: [:active, :ban] #enum
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  #для добавление строки name
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end

  
  #вывод ошибок для пользователя
  def render_404
    render file: 'public/404.html', status: 404
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to post_path(@post)

  end


  private

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController

  before_action :set_history, only: [:show, :edit, :update, :destroy]

  def index
    @histories = History.all
  end

  def show
  end

  def new
    @history = History.new
  end

  def create
    @history = History.create(history_params)
    if @history.save
      flash[:success] = 'История создана!'
      redirect_to @history
    else
      flash.now[:error] = 'История не создана'
      render 'new'
    end
  end


  def edit
  end

  def update
    @history.update_attributes(history_params)
    if @history.save
      flash[:success] = 'История отредактирована!'
      redirect_to @history
    else
      flash.now[:error] = 'Ошибка!'
      render 'edit'
    end
  end


  def destroy
    @history.destroy
    flash[:success] = 'Статья удалена!'
    redirect_to histories_path
  end




  private

  def history_params
    params.require(:history).permit(:title, :body, :source, :image)
  end


  def set_history
    @history = History.find(params[:id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.create(user_id: current_user.id, post_id: @post.id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 2) # для отображение тэгов
    else
      @posts = Post.paginate(page: params[:page], per_page: 2) #gem will_paginate
      @posts = @posts.published #выводить посты с status(published)
    end
  end

  def show
  end

  def new
    @post = Post.new
  end


    def create
      @post = current_user.posts.new(post_params)
      if @post.save
        flash[:success] = 'Статья создана!'
        redirect_to @post
      else
        flash.now[:error] = 'Статья не создана'
        render :new
      end
    end


  def edit
  end

  def update
    @post.update_attributes(post_params)
    if @post.save
      flash[:success] = 'Статья обновлена!'
      redirect_to @post
    else
      flash.now[:error] = 'Ошибка!'
      render 'edit'
    end
  end


  def destroy
    @post.destroy
    flash[:success] = 'Статья удалена!'
    redirect_to posts_path
  end


  private

  def post_params
    params.require(:post).permit(:title, :body, :image, :tag_list, :status )
  end


  def set_post
    @post = Post.where(id: params[:id]).first
    render_404 unless @post # выовд 404 если не получим :id

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<% if comment.body? %>
  <div>
    <p>User: <%= comment.user.name %></p>
    <p>Body: <%= comment.body %></p>
    <small><%= comment.created_at %></small>
    <hr>
  </div>

<%end %>

app/views/comments/_form.html.erb
<%= form_for ([@post, @post.comments.build]) do |f| %> <!--[Post.find(params[:id]), Post.commetns.new]) -->

  <div>
    <%= f.text_area :body, cols: 10, rows: 1  %>
    <%= f.submit 'Сохранить' %>
  </div>
<%end %>

app/views/histories/_form.html.erb
<%= form_for @history do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.trix_editor :body, class: 'editor' %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.label :source %>
    <%= f.text_field :source %>
  </div>

  <div class="form-group">
    <%= f.submit 'сохранить' %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h1>history-edit</h1>

<%= render 'histories/form' %>

app/views/histories/index.html.erb
<h1>History-index</h1>

<% @histories.each do |h| %>
    <p>id: <%= h.id %></p>
    <p>title: <%= link_to h.title, history_path(h) %></p>
  <small>
    <%= link_to 'удалить', history_path(h), method: :delete  %>
    <%= link_to 'изменить', edit_history_path(h)  %>
  </small>
    <p>body: <%= h.body.html_safe %></p>
  <% if h.image.present? %>
    <%= image_tag h.image.variant(resize: "100x100") %><!-- для ActivaStorage -->
  <%end %>
    <p>source<%= h.source %></p>
    <hr>
<%end %>

app/views/histories/new.html.erb
<h1>history-new</h1>

<%= render 'histories/form' %>

app/views/histories/show.html.erb
<h1>History-show</h1>

<p>title: <%= @history.title %></p>
<p>body: <%= @history.body.html_safe %></p>
<% if @history.image.present? %>
  <%= image_tag @history.image.variant(resize: "200x200") %>
<%end %>
<p>source: <%= @history.source %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AsiteV2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= link_to 'все статьи | ', posts_path %>
    <%= link_to 'истории | ', histories_path %>
    <% if user_signed_in? %>
      <% if current_user.active? %>
        <%= link_to 'новая статья | ', new_post_path %>
        <%= link_to 'добавить историю', new_history_path %>
      <%end %>
    <%end %>

    <% if user_signed_in? %>
      <%= link_to '| Выйти', destroy_user_session_path, :method => :delete %>
      <%= current_user.name %>
    <% else %>
      <%= link_to 'Войти', new_user_session_path, class: 'mr-4 all_posts' %>
      <%= link_to 'Зарегистрироваться', new_user_registration_path, class: 'all_posts mr-2'%>
    <% end %>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <p class="flash_error"><%= flash[:error] %></p>
    <p class="flash_success"><%= flash[:success] %></p>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.trix_editor :body, class: 'editor' %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list %>
  </div>

  <div class="form-group">
    <%= f.submit 'сохранить' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>edit</h1>

<%= render 'posts/form' %>

app/views/posts/index.html.erb
<h1>inddex</h1>

<!--для отображение Tags -->
  <div id="tag_cloud">
    <% tag_cloud Post.tag_counts, %[s m l] do |tag, css_class| %>
      <small><%= link_to tag.name, tag_path(tag.name), class: css_class %></small>
    <% end %>
  </div>
  <hr>


<% @posts.each do |p| %>
  <p>id: <%= p.id %> (<small> status: <%= p.status %></small>)</p>
  <p>user: <%= p.user.name %></p>
  <p>title: <%= link_to p.title, post_path(p) %></p>
  <p>Tags: <%= raw p.tag_list.map { |t| link_to t, tag_path(t)}.join(', ') %></p> <!-- для tags -->
  <p>body: <%= p.body.html_safe %></p> <!--.html.save для trix -->
  <%# if p.image.present? %>
<!--    <%#= image_tag p.image.variant(resize: "100x100") %><!-- для ActivaStorage -->-->
  <%#end %>
  <br>
  <small>
    <%= link_to 'удалить', post_path(p), method: :delete  %>
    <%= link_to 'изменить', edit_post_path(p)  %>
  </small>
  <p><%= link_to 'Like', post_likes_path(p), method: :post, class: 'like like_posts p-3', id: 'like' %><%=  p.likes.count %></p>
  <p><%= link_to 'Comments', post_path(p) %><%=  p.comments.count %></p>

  <hr>
<% end %>

<%= will_paginate @posts %>


<h1>asdasdasd</h1>

app/views/posts/new.html.erb
<h1>post-new</h1>

<%= render 'posts/form' %>

app/views/posts/show.html.erb
<h1>show</h1>

<p>user: <%= @post.user.name %></p>
<p>title: <%= @post.title %></p>
<p>body: <%= @post.body.html_safe %></p><!-- .html_safe - для trix-->
<%# if @post.image.present? %>
  <%#= image_tag @post.image.variant(resize: "200x200") %>
<%#end %>

<% if user_signed_in? %>
  <% if current_user.active? %>
   <%= render 'comments/form' %>
  <%end %>
<%end %>

<h3 >Комментарии <%= @post.comments.count %></h3>
<div>
  <% @post.comments.each do |cmt| %>
    <%= render 'comments/comment', comment: cmt %>
  <%end %>
</div>